### ISSUE TITLE
App crashes on launch when using SDK version 4.9.0

### ISSUE THREAD

**Issue by NickGraeff** [iovation/launchkey-android-authenticator-sdk#45]
When launching the app after including the SDK and minifying the app in debug/release modes the following exception arose upon launching the app 
```
2020-02-05 11:22:20.143 11729-11729/com.some.company.app E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.some.company.app, PID: 11729
    java.lang.RuntimeException: Unable to get provider com.launchkey.android.authenticator.sdk.init.AuthSdkInitProvider: java.lang.ClassNotFoundException: Didn't find class "com.launchkey.android.authenticator.sdk.init.AuthSdkInitProvider" on path: DexPathList[[zip file "/data/app/com.some.company.app-OlSQdkA-12LEJsPT7kRSDg==/base.apk"],nativeLibraryDirectories=[/data/app/com.some.company.app-OlSQdkA-12LEJsPT7kRSDg==/lib/x86, /data/app/com.some.company.app-OlSQdkA-12LEJsPT7kRSDg==/base.apk!/lib/x86, /system/lib, /system/product/lib]]
        at android.app.ActivityThread.installProvider(ActivityThread.java:6988)
        at android.app.ActivityThread.installContentProviders(ActivityThread.java:6528)
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6445)
        at android.app.ActivityThread.access$1300(ActivityThread.java:219)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1859)
        at android.os.Handler.dispatchMessage(Handler.java:107)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:7356)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)
     Caused by: java.lang.ClassNotFoundException: Didn't find class "com.launchkey.android.authenticator.sdk.init.AuthSdkInitProvider" on path: DexPathList[[zip file "/data/app/com.some.company.app-OlSQdkA-12LEJsPT7kRSDg==/base.apk"],nativeLibraryDirectories=[/data/app/com.some.company.app-OlSQdkA-12LEJsPT7kRSDg==/lib/x86, /data/app/com.some.company.app-OlSQdkA-12LEJsPT7kRSDg==/base.apk!/lib/x86, /system/lib, /system/product/lib]]
        at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:196)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
        at android.app.AppComponentFactory.instantiateProvider(AppComponentFactory.java:147)
        at android.support.v4.app.CoreComponentFactory.instantiateProvider(CoreComponentFactory.java:62)
        at android.app.ActivityThread.installProvider(ActivityThread.java:6972)
        at android.app.ActivityThread.installContentProviders(ActivityThread.java:6528) 
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6445) 
        at android.app.ActivityThread.access$1300(ActivityThread.java:219) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1859) 
        at android.os.Handler.dispatchMessage(Handler.java:107) 
        at android.os.Looper.loop(Looper.java:214) 
        at android.app.ActivityThread.main(ActivityThread.java:7356) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930) 
```

**Comment by NickGraeff** [comment]
The above issue occurs when the app is minified but the proper proguard keep lines were not added.
Please make sure the following lines are in your proguard file:
```
-keep class org.spongycastle.jce.** { *; }
-keep class org.spongycastle.jcajce.** { *; }
```
